---
deployment:
  tasks:
    - export DEPLOYPATH=/home/csdev/community.codesociety.dev/
    - /home/csdev/repositories/codesociety-community/ index.html $DEPLOYPATH
    - /home/csdev/repositories/codesociety-community/ -R css $DEPLOYPATH
    - /home/csdev/repositories/codesociety-community/ -R images $DEPLOYPATH
    - /home/csdev/repositories/codesociety-community/ -R js $DEPLOYPATH